
version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: soulscout_prometheus
    restart: unless-stopped
    networks:
      - soulscout_net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:10.0.0
    container_name: soulscout_grafana
    restart: unless-stopped
    networks:
      - soulscout_net
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
      GF_USERS_ALLOW_SIGN_UP: false
    secrets:
      - grafana_admin_password

volumes:
  prometheus_data:
  grafana_data:

networks:
  soulscout_net:
    external: true

secrets:
  grafana_admin_password:
    file: /home/leland/Desktop/Code/SolScout_v1.1/secrets/grafana_admin_password
