
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'soulscout-services'
    static_configs:
      - targets:
          - 'tg_gateway:8080'
          - 'portfolio:8081'
          - 'ingestor:8082'
          - 'analytics:8083'
          - 'notifier:8084'
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
